apiVersion: v1
kind: ConfigMap
metadata:
  name: nodeapp-config
  namespace: devsecops
data:
  APP_ENV: "production"
  NODE_ENV: "production"
  PORT: "3000"
  RATE_LIMIT_WINDOW_MS: "60000"
  RATE_LIMIT_MAX: "100"
  APP_DB_NAME: "devsecops"
  APP_DB_AUTHDB: "devsecops"
