apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devsecops
resources:
  - namespace.yaml
  - podsecurity.yaml
  - serviceaccount-rbac.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - hpa.yaml
  - pdb.yaml
