apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  namespace: devsecops
  labels:
    app: nodeapp
spec:
  type: ClusterIP
  selector:
    app: nodeapp
  ports:
    - name: http
      port: 3000
      targetPort: 3000
