apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodeapp
  namespace: devsecops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nodeapp-read-config
  namespace: devsecops
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nodeapp-read-config
  namespace: devsecops
subjects:
  - kind: ServiceAccount
    name: nodeapp
    namespace: devsecops
roleRef:
  kind: Role
  name: nodeapp-read-config
  apiGroup: rbac.authorization.k8s.io
